# BIENVENU ! MODIFIER ICI LES PARAMETRES DE VOTRE PLATEFORME KATALOG
# --------------------------------------------------------------------------------------------------------------------------------------------------
#
# Konsilion - Licence juridique Creative Commons CC-BY-NC
# --------------------------------------------------------------------------------------------------------------------------------------------------



# SITE INFORMATIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

site_name: LowTRE - Plateforme de ressources ouvertes
site_author: Université Grenoble-Alpes
site_description: Une plateforme de science ouverte et open-data, pour la Low-technologie, la recherche et l'enseignement.





# LANGUE, COULEURS et LOGO
# --------------------------------------------------------------------------------------------------------------------------------------------------

theme:
    language: fr
    palette:
        primary: grey
        accent: blue
    logo: https://raw.githubusercontent.com/nbrem/lowtre-katalog/master/docs/etc/logo-carre-lowtre.png
    favicon: https://raw.githubusercontent.com/nbrem/lowtre-katalog/master/docs/etc/logo-carre-lowtre.png

# [Liste des couleurs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)





# MENTIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

copyright: LowTRE - Licence juridique Creative Commons CC-BY-SA 4.0
















      
 



















# ============  /!\ NE PAS MODIFIER /!\ - procedure d'appel du fichier 'env' pour le parametrage  ============

INHERIT: ./docs/env  
